[build]
builder = "nixpacks"
buildCommand = "echo 'Building...'"

[deploy]
startCommand = "echo 'Starting...'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service.backend]
rootDirectory = "/backend"
buildCommand = "npm install"
startCommand = "npm start"

[service.frontend]
rootDirectory = "/frontend"
buildCommand = "cd frontend && npm cache clean --force && rm -rf node_modules package-lock.json && npm install --no-package-lock && npm install react-select@5.10.1 --save && npm run build"
startCommand = "cd frontend && npm run railway" 