[build]
builder = "nixpacks"
buildCommand = "echo 'Building...'"

[deploy]
startCommand = "echo 'Starting...'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service.backend]
rootDirectory = "/backend"
buildCommand = "npm install"
startCommand = "npm start"

[service.frontend]
rootDirectory = "/frontend"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm run railway" 