[build]
builder = "nixpacks"
buildCommand = "echo 'Building...'"

[deploy]
startCommand = "echo 'Starting...'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service.backend]
rootDirectory = "/backend"
buildCommand = "npm install"
startCommand = "npm start"

[service.frontend]
rootDirectory = "/frontend"
buildCommand = "cd frontend && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm install typescript@4.9.5 --save-exact && npm run build"
startCommand = "cd frontend && npm run railway" 